### ISSUE TITLE
Difference between "License Description" and Licenses"

### ISSUE THREAD

**Issue by jayvdb** [raratiru/django-quenv#15]
I see a few cases where License Description" and "Licenses" are very different/confusing.  e.g.

```
Package: django-static-jquery-ui
License Description: Private
Lines of Code: 0
Grade: 0
Licenses: MIT License
```

```
Package: GitPython
License Description: UNKNOWN
Lines of Code: 9367
Grade: C
Licenses: BSD License
```

```
Package: django-oscar-eurotaxes
License Description: Copyright (c) 2011, Tangent Communications PLC and individual contributors.
Lines of Code: 0
Grade: 0
Licenses: BSD License
Date Checked: 2020-08-03
```

```
Package: shouldbe
License Description: LICENSE.txt
Lines of Code: 0
Grade: 0
Licenses: ISC License (ISCL)
```

The "License Description" is being used in the list view filter (i.e. `/admin/quenv/info/`), whereas the "Licenses" field seems to be the better field value.

**Comment by raratiru** [comment]
I made that choice because in my (limited) package collection the description was more explicit. For example the license is BSD but the description specifies the flavor which is more informative:

```

Package: thepysec
License Description: BSD 3-Clause License
Lines of Code: 305
Grade: A+
Licenses: BSD License
Date Checked: 2020-08-02
```

In fact, choosing either one field or the other cannot be justified because their contents seem to be completely random.

However:

Clicking in the package, the information is there. 

More important is that on the right hand where all licenses are listed, the "hidden" license is also there. Therefore `GitPython` appears when filtering either 

* by license `UNKNOWN` -> `/quenv/info/?license=UNKNOWN`
* by `BSD License ' -> `/quenv/info/?license=BSD+License`

Another idea would be to merge those fields but I really cannot understand the logic behind their separate existence or why this logic is randomly followed.

Quenv tries to gather all available info, but does not succeed in presenting it in one page or cannot promise 100% accuracy. It just gives a hint where it is necessary to dig deeper or not. 

Even its code base quality will not allow us to expect more than a rough or blurry overview of what is going on under the hood in the deepest areas of packages where care is not given but grounds for legal issues are provided. 

It is just an overview in an area totally hidden: 

* If you read the license of a package before installing it, *it does* make a difference when its license changes. However, `pip install -U` will not bring it forth. Quenv, can ring a bell and at least urge you to visit the relevant github page for further understanding.

* If this package has dependencies, quenv will list them in the daily changes and try to provide info about the licenses or their quality.

Therefore, the choice was based on the feeling of my collection at that time (rough time, judging from my coding!) and it was the result of tossing a coin because this seems to be the best criterion for making that choice!
